### ISSUE TITLE
Plan execution

### ISSUE THREAD

**Issue by Flesh-Engine** [Joy-less/GameReadyGoap#1]
Dear,

It is unclear to me on how you actually need to execute a given plan, this is also not explained in the readme.md.
If you could please add this to the readme.md that would be grand.

As far is I understand it, after formulating a plan, we'll need to execute it using "GoapPlan.Execute(GoapAgent, Func<GoapAction,bool>)"
but what do I pass to the "Func<GoapAction,bool>"?  The plan already contains the actions it needs to perform, what actually am I passing here?

Kindly expand the provided example to include this.

**Comment by Joy-less** [comment]
Hello @Flesh-Engine,
Thank you for using this library.
While the plans contain the actions, they don't contain the execution methods. You should pass a function that takes an action, executes it, and returns whether the execution was successful (otherwise the plan is cancelled).
For example:
```cs
Plan.Execute(Agent, Action => {
    if (Action.Name == "Jump") {
        if (AlreadyJumping) {
            return false; // failed to jump
        }
        Jump();
        return true;
    }
    return false; // action not found
});
```

Alternatively, you can avoid using `Execute`, since it's a simple helper method. This is the code inside the `Execute` method:
```cs
/// <summary>
/// Executes each action if valid and successful.
/// </summary>
/// <returns>true if finished.</returns>
public bool Execute(GoapAgent Agent, Func<GoapAction, bool> ExecuteAction) {
    foreach (GoapAction Action in Actions) {
        if (!Agent.IsActionValid(Action)) {
            return false;
        }
        if (!ExecuteAction(Action)) {
            return false;
        }
    }
    return true;
}
```

**Comment by Flesh-Engine** [comment]
Hi @Joy-less ,

That's what I assumed, but what is the use case for having it work like this?

I've tried returning true in the lambda, but, as you can see from the snippet you posted; the GoapAction just doesn't *do* anything to the Agent, nor does it apply its effects.
Currently, it seems like these are only useful for formulating a plan, not executing it.

I suggest that the GoapAction be expanded with a property that houses the delegate to be executed.
Then the GoapPlan.Execute could have an overload that executes the GoapAction's method (if requirements are met) and applies the GoapEffects to the passed GoapAgent's state when the GoapAction's delegate method returns true.

As it stands, currently, imho the library doesn't offer plan execution at all since we need to effectively create a "tree" for planning and then a 'lambda' 'tree' for execution.

EDIT:
Working Suggestion:
```
public class ImprovedGoapAction : GoapAction
{
    public required Func<bool> Executee = () => true;

    public ImprovedGoapAction(object? Name = null) : base(Name)
    { }
    [SetsRequiredMembers]
    public ImprovedGoapAction(object? Name, List<GoapEffect> Effects) : this(Name, Effects, () => true)
    { }
    [SetsRequiredMembers]
    public ImprovedGoapAction(object? Name, List<GoapEffect> Effects, Func<bool> Executee) : base(Name, Effects)
    {
        this.Executee = Executee;
    }

    public bool ExectueAction(GoapAgent Agent)
    {
        if (Executee())
        {
            for (var i = 0; i < Effects.Count; i++)
            {
                Agent.States[Effects[i].State] = Effects[i].Operation.Operate(Agent.States[Effects[i].State], Effects[i].Value.Evaluate(Agent.States));
            }
            return true;
        }
        return false;
    }
}
```
Called:
```
private static void Demo()
{
    GoapAgent Farmer = new("Farmer")
    {
        States = new()
        {
            ["Energy"] = 100,
            ["CropHealth"] = 0,
        },
        Goals = [
            new GoapGoal("TendToCrops") {
                Objectives = [
                    new GoapCondition("CropHealth", GoapComparison.GreaterThanOrEqualTo, 100){BestEffort = true}
                ]
            }
        ],
        Actions = [
            //new GoapAction("Farm") {
            new ImprovedGoapAction("Farm"){
                    Effects = [
                            new GoapEffect("CropHealth",GoapOperation.IncreaseBy,20)
                        ,   new GoapEffect("Energy", GoapOperation.DecreaseBy,30)
                    ]
                ,   Requirements = [
                            new GoapCondition("Energy", GoapComparison.GreaterThanOrEqualTo, 30)
                    ]
                ,   Executee = ()=>true
            },
            //new GoapAction("Sleep") { Effects = [ new GoapEffect("Energy",GoapOperation.IncreaseBy,5) ] }
            new ImprovedGoapAction("Sleep") { Effects = [ new GoapEffect("Energy",GoapOperation.IncreaseBy,5) ], Executee=()=>true }
        ]
    };

    GoapPlan plan = Farmer.FindPlan() ?? throw new ArgumentNullException();
    Console.WriteLine("Action\tEnergy\tCropHealth");
    plan.Execute(Farmer, Action =>
    {
        Console.WriteLine("{0}\t{1}\t{2}", Action.Name, Farmer.GetState<int>("Energy"), Farmer.GetState<int>("CropHealth"));
        if (Action is ImprovedGoapAction impAction) return impAction.ExectueAction(Farmer);
        return true;
    });
    Console.WriteLine("{0}\t{1}\t{2}", "---", Farmer.GetState<int>("Energy"), Farmer.GetState<int>("CropHealth"));
}
```
Produces the desired output of;
![image](https://github.com/user-attachments/assets/9f762081-ebe4-4bb7-a449-315d3ff78f05)

Of course, the "Action is ImprovedGoapAction" is superfluous in case of implmentation.

**Comment by Joy-less** [comment]
Hi @Flesh-Engine
This is a good point. The original idea is that states are set through sensors rather than changed by actions (e.g. the "attack player" action would not reduce the player health state, instead it would wait for the player health state to be externally sensed). I did not anticipate your use case that doesn't use sensors. I think it's a good idea and will look to implement it soon.

**Comment by Joy-less** [comment]
This has been changed in `v6.0`. Please download that version and let me know if you have problems.
Thank you
